### ISSUE TITLE
Erros after make -j12 command on M1 Mac

### ISSUE THREAD

**Issue by oguzveozturk** [moetsi/Sensor-Stream-Pipe#18]
Hi,
I'm using M1 macbook air (Monterey 12.6) and getting the following errors after the **make -j12** command:

![Ekran Resmi 2022-10-28 14 17 23](https://user-images.githubusercontent.com/54209230/198579756-2c520d04-b44d-4061-a683-eac73eb7647c.jpg)
![Ekran Resmi 2022-10-28 14 17 33](https://user-images.githubusercontent.com/54209230/198579760-6aec1662-e7a2-4464-b1f1-21def15226cd.jpg)
![Ekran Resmi 2022-10-28 14 17 46](https://user-images.githubusercontent.com/54209230/198579764-f56a8157-3033-4c86-bf72-4fe4d0ad5cbe.jpg)
![Ekran Resmi 2022-10-28 14 18 14](https://user-images.githubusercontent.com/54209230/198579767-32fa225b-0f40-4641-91bf-2999151feb63.jpg)

**Comment by adammpolak** [comment]
Thank you for opening the issue. We have not tested SSP with the new Mac hardware and will look into this.

What is your use case?

**Comment by oguzveozturk** [comment]
I just want to try 3d streaming from iPhone to M1 Mac. but I couldn't install on m1 Mac. Most of the errors are caused by installing x86 on arm64 architecture.

**Comment by adammpolak** [comment]
@oguzveozturk I believe this could be fixed by building the 3rd party dependencies yourself for your platform. Right now we pre-bundle for users.

You can run the .sh scripts in 3rdparty: https://github.com/moetsi/Sensor-Stream-Pipe/blob/master/3rdparty/build_ios_dep.sh

This should have it built for your platform, you can then replace with THESE libraries.

I believe it should work.

**Comment by adammpolak** [comment]
@oguzveozturk I assume this ticket is closed

**Comment by adammpolak** [comment]
@oguzveozturk  I pushed an update, works now.
